#!/bin/bash

docker rm --force neo4j
docker build -t neo4j:1.0 .
docker run \
	--name neo4j \
	-it \
	--network="host" \
	--mount source=neo4jvol,target=/var/lib/neo4j/data \
	neo4j:1.0 \
	/bin/bash -c "./neo4j start && /bin/bash"